name: beamwise
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - ca-certificates=2023.08.22
  - ld_impl_linux-64=2.38
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - ncurses=6.4
  - openssl=3.0.11
  - pip=23.2.1
  - python=3.8.18
  - readline=8.2
  - setuptools=68.0.0
  - sqlite=3.41.2
  - tk=8.6.12
  - wheel=0.41.2
  - xz=5.4.2
  - zlib=1.2.13
  - pip:
      - absl-py==2.0.0
      - cachetools==5.3.1
      - certifi==2023.7.22
      - charset-normalizer==3.3.0
      - cmake==3.27.6
      - contourpy==1.1.1
      - cycler==0.12.1
      - filelock==3.12.4
      - fonttools==4.43.1
      - fsspec==2023.9.2
      - google-auth==2.23.3
      - google-auth-oauthlib==1.0.0
      - grpcio==1.59.0
      - huggingface-hub==0.18.0
      - idna==3.4
      - importlib-metadata==6.8.0
      - importlib-resources==6.1.0
      - jinja2==3.1.2
      - joblib==1.3.2
      - kiwisolver==1.4.5
      - lit==17.0.2
      - markdown==3.5
      - markupsafe==2.1.3
      - matplotlib==3.7.3
      - mpmath==1.3.0
      - networkx==3.1
      - numpy==1.24.4
      - nvidia-cublas-cu11==11.10.3.66
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu11==11.7.101
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu11==11.7.99
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu11==11.7.99
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu11==8.5.0.96
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu11==10.2.10.91
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu11==11.4.0.1
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu11==11.7.4.91
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu11==2.14.3
      - nvidia-nccl-cu12==2.18.1
      - nvidia-nvjitlink-cu12==12.2.140
      - nvidia-nvtx-cu11==11.7.91
      - nvidia-nvtx-cu12==12.1.105
      - oauthlib==3.2.2
      - opencv-python==4.8.1.78
      - packaging==23.2
      - pandas==2.0.3
      - pillow==10.0.1
      - prettytable==3.9.0
      - protobuf==4.24.4
      - pyasn1==0.5.0
      - pyasn1-modules==0.3.0
      - pykalman==0.9.5
      - pyparsing==3.1.1
      - python-dateutil==2.8.2
      - pytz==2023.3.post1
      - pyyaml==6.0.1
      - requests==2.31.0
      - requests-oauthlib==1.3.1
      - rsa==4.9
      - safetensors==0.4.0
      - scikit-learn==1.3.1
      - scipy==1.10.1
      - six==1.16.0
      - sympy==1.12
      - tensorboard==2.14.0
      - tensorboard-data-server==0.7.1
      - threadpoolctl==3.2.0
      - timm==0.9.7
      - torch==2.0.1
      - torchvision==0.15.2
      - tqdm==4.66.1
      - triton==2.0.0
      - typing-extensions==4.8.0
      - tzdata==2023.3
      - urllib3==2.0.6
      - utm==0.7.0
      - wcwidth==0.2.8
      - werkzeug==3.0.0
      - zipp==3.17.0
